### ISSUE TITLE
Blurred UIImageView twitch issue inside UITableViewCell

### ISSUE THREAD

**Issue by EvgenyKarkan** [nicklockwood/FXBlurView#122]
I'm using v1.6.4 to blur UIImageVIew content. 
Everything is OK until I start to scroll. 
While scrolling - blurred image begin to twitch.
I recorded video sample, see this issue at the top of image - https://monosnap.com/file/rXE6SEV9N0SxTqCpHHFVUI5RbsBNwe

How can I fix that?

**Comment by Hackice** [comment]
set dynamic to NO.
