### ISSUE TITLE
Issues with trying to take a screenshot of a view with an FXBlurView on top. 

### ISSUE THREAD

**Issue by Brown-amazingness** [nicklockwood/FXBlurView#123]
I have a section of my app that contains a blurred image, and if you try to save the image with the following code, the blur will result in lots of squares, which is not aesthetically appealing.

Here is the following code for taking the screenshot
```-(void)screenshotAndSaveImage
{
    
    UIView *wholeScreen = self.pictureView;
    
    // define the size and grab a UIImage from it
    UIGraphicsBeginImageContextWithOptions(wholeScreen.bounds.size, wholeScreen.opaque, 0.0);
    [wholeScreen.layer renderInContext:UIGraphicsGetCurrentContext()];
    UIImage *screengrab = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    UIImageWriteToSavedPhotosAlbum(screengrab, nil, nil, nil);
    
}

**Comment by nicklockwood** [comment]
Try capturing the screenshot using `-[UIView drawViewHierarchyInRect:afterScreenUpdates:]` instead.

**Comment by Brown-amazingness** [comment]
Adding `[wholeScreen.layer drawViewHierarchyInRect:self.view.bounds afterScreenUpdates:YES];` fixes the issue. Closing now.
