### ISSUE TITLE
Numerous errors in console when blurring images on Simulator

### ISSUE THREAD

**Issue by DenHeadless** [nicklockwood/FXBlurView#133]
Hey!

I'm receiving multiple error messages in console, when blurring image on iPhone Simulator and blurring does not seem to work:

```
CGBitmapContextCreate: unsupported parameter combination: set CGBITMAP_CONTEXT_LOG_ERRORS environmental variable to see the details
<Error>: CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
```

It seems that fix for this problem was merged into master in #86, however it got reverted with b49c74700b2d80a3bf451128c992fda69330512d. Was this intentional or was it a mistake?

If it's a mistake, i can open PR to fix this issue. I tried locally and images started blurring correctly without any error messages, however I'm not sure that this would not break something else you've been doing on 1.6.4 release.

/cc @nicklockwood.

P.S. Xcode 8, iOS 10 simulator.

**Comment by ron137** [comment]
+1

**Comment by sugite** [comment]
http://stackoverflow.com/questions/5545600/iphone-cgcontextref-cgbitmapcontextcreate-unsupported-parameter-combination/7868973
