### ISSUE TITLE
Setting cornerRadius on FXBlurView's CALayer doesn't work

### ISSUE THREAD

**Issue by egold** [nicklockwood/FXBlurView#20]
Subclassing FXBlurView, I have tried:

```
#import <QuartzCore/QuartzCore.h>

...

-(void)awakeFromNib {
    self.layer.cornerRadius = 15.0;
}
```

It works fine if I change the superclass to UIView, but when using FXBlurView as the parent class, the corner radius remains 0.0.

**Comment by hashemp206** [comment]
I want to add drop shadow to FXBlurView but setting masks to bounds clips drop shadow!! what to do? disabling masks to bounds result in view without any corner radius!!
