### ISSUE TITLE
Blurring doesn't work when added on top window in iOS 8

### ISSUE THREAD

**Issue by itsmeichigo** [nicklockwood/FXBlurView#90]
I'm trying to add blur view on the top window to blur everything in the background including the navigation bar. This is what I'm doing:

``` objective-C
UIWindow *topWindow = [[[UIApplication sharedApplication].windows sortedArrayUsingComparator:^NSComparisonResult(UIWindow *win1, UIWindow *win2) {
        return win1.windowLevel - win2.windowLevel;
    }] lastObject];
    [topWindow addSubview:self.blurView];
```

This works on iOS 7 but not 8. Please take a look at this problem and thanks.

**Comment by daspisch** [comment]
Try to avoid adding views directly in window. It's better to take a rootView from rootWindow and add blur view in it. After it you must set underlyingView of blur view to rootView, because BlurView must know what to blur.
